[program:buildwithabdallah-api-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php8.5 -d memory_limit=256M /home/buildwithabdallah-api/htdocs/www.api.buildwithabdallah.com/artisan queue:work database --sleep=3 --tries=5 --max-time=1800 --max-jobs=1000 --timeout=60 --queue=whatsapp-webhooks,whatsapp-outbound,application-events,default
directory=/home/buildwithabdallah-api/htdocs/www.api.buildwithabdallah.com
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=buildwithabdallah-api
numprocs=1
redirect_stderr=true
stdout_logfile=/home/buildwithabdallah-api/htdocs/www.api.buildwithabdallah.com/storage/logs/worker.log
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=5
stopwaitsecs=3600
startsecs=1
startretries=3
