[program:buildwithabdallah-api-scheduler]
process_name=%(program_name)s
command=/usr/bin/php8.5 /home/buildwithabdallah-api/htdocs/www.api.buildwithabdallah.com/artisan schedule:work
directory=/home/buildwithabdallah-api/htdocs/www.api.buildwithabdallah.com
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=buildwithabdallah-api
numprocs=1
redirect_stderr=true
stdout_logfile=/home/buildwithabdallah-api/htdocs/www.api.buildwithabdallah.com/storage/logs/scheduler.log
stdout_logfile_maxbytes=5MB
stdout_logfile_backups=3
stopwaitsecs=60
startsecs=1
startretries=3
